create temp table content_fixture(k text primary key,id uuid);
grant select on content_fixture to authenticated;
insert into content_fixture select 'pm',u.id from app_user u join security_role r on r.id=u."roleId" where r.name='Project Manager' and u.status='ACTIVE' and u."deletedAt" is null limit 1;
insert into content_fixture select 'contributor',u.id from app_user u join security_role r on r.id=u."roleId" where r.name='Consultant' and u.status='ACTIVE' and u."deletedAt" is null limit 1;
insert into content_fixture values('project',gen_random_uuid()),('task',gen_random_uuid());
do $$ begin if (select count(*) from content_fixture)<>4 then raise exception 'Missing fixtures'; end if; end $$;
insert into project(id,"projectNumber",name,"projectManagerId","projectType","billingType", "updatedAt") values((select id from content_fixture where k='project'),'CONTENT-TEST','Content planning test',(select id from content_fixture where k='pm'),'INTERNAL','FIXED',now());
insert into project_task(id,"projectId",name,"assignedUserId","updatedAt") values((select id from content_fixture where k='task'),(select id from content_fixture where k='project'),'Content test task',(select id from content_fixture where k='contributor'),now());
insert into project_member("projectId","userId",active,"projectRole","updatedAt") values((select id from content_fixture where k='project'),(select id from content_fixture where k='contributor'),true,'Writer',now());
create temp table content_payload as select '{"channel":"INSTAGRAM","format":"POST","objective":"Awareness","audience":"Retailers","brief":"Product introduction","plannedPublishAt":"2026-10-01T19:00:00Z","clientApprovalRequired":true}'::jsonb as plan;
grant select on content_payload to authenticated;
insert into content_fixture values('v1',gen_random_uuid()),('v2',gen_random_uuid()),('v3',gen_random_uuid()),('internal',gen_random_uuid()),('client',gen_random_uuid()),('publication',gen_random_uuid());
select set_config('request.jwt.claim.sub',(select id::text from content_fixture where k='pm'),true);
set local role authenticated;
select save_content_plan((select id from content_fixture where k='task'),0,(select plan from content_payload));
reset role;
select set_config('request.jwt.claim.sub',(select id::text from content_fixture where k='contributor'),true);
set local role authenticated;
do $$ declare tid uuid:=(select id from content_fixture where k='task'); vid uuid:=(select id from content_fixture where k='v1'); denied boolean; begin
 perform add_content_version(vid,tid,0,1,'First caption',null,null);
 perform add_content_version(vid,tid,0,1,'First caption',null,null);
 if (select count(*) from content_version where "taskId"=tid)<>1 then raise exception 'Duplicate retry'; end if;
 denied:=false; begin perform review_content_version(gen_random_uuid(),vid,'INTERNAL','APPROVED','Self approval',null); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Contributor approved'; end if;
 denied:=false; begin perform record_content_publication(gen_random_uuid(),vid,'https://example.com/post',now()); exception when invalid_parameter_value then denied:=true; end;
 if not denied then raise exception 'Unapproved publication recorded'; end if;
 denied:=false; begin update content_version set copy='Tampered' where id=vid; exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Version mutable'; end if;
 denied:=false; begin perform add_content_version(gen_random_uuid(),tid,0,1,'Stale version'); exception when serialization_failure then denied:=true; end;
 if not denied then raise exception 'Stale version saved'; end if;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from content_fixture where k='pm'),true);
set local role authenticated;
do $$ declare vid uuid:=(select id from content_fixture where k='v1'); denied boolean; published timestamptz; begin
 denied:=false; begin perform review_content_version(gen_random_uuid(),vid,'CLIENT','APPROVED','Email reference','Client'); exception when invalid_parameter_value then denied:=true; end;
 if not denied then raise exception 'Client review preceded internal approval'; end if;
 perform review_content_version((select id from content_fixture where k='internal'),vid,'INTERNAL','APPROVED','Copy and asset checked');
 perform review_content_version((select id from content_fixture where k='internal'),vid,'INTERNAL','APPROVED','Copy and asset checked');
 denied:=false; begin perform record_content_publication(gen_random_uuid(),vid,'https://example.com/post',now()); exception when invalid_parameter_value then denied:=true; end;
 if not denied then raise exception 'Missing client approval ignored'; end if;
 perform review_content_version((select id from content_fixture where k='client'),vid,'CLIENT','APPROVED','Received approval email reference','Client reviewer');
 denied:=false; begin perform record_content_publication(gen_random_uuid(),vid,'https://example.com/old',now()-interval '1 day'); exception when invalid_parameter_value then denied:=true; end;
 if not denied then raise exception 'Publication backdated before approval'; end if;
 published:=clock_timestamp();
 perform record_content_publication((select id from content_fixture where k='publication'),vid,'https://example.com/post',published);
 perform record_content_publication((select id from content_fixture where k='publication'),vid,'https://example.com/post',published);
 if (select count(*) from content_publication where "versionId"=vid)<>1 then raise exception 'Duplicate publication'; end if;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from content_fixture where k='contributor'),true);
set local role authenticated;
select add_content_version((select id from content_fixture where k='v2'),(select id from content_fixture where k='task'),1,1,'Changed caption','https://example.com/frozen-asset',repeat('a',64));
do $$ declare denied boolean:=false; begin
 begin perform record_content_publication(gen_random_uuid(),(select id from content_fixture where k='v2'),'https://example.com/changed',now()); exception when invalid_parameter_value then denied:=true; end;
 if not denied then raise exception 'New version inherited approval'; end if;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from content_fixture where k='pm'),true);
set local role authenticated;
do $$ declare denied boolean; vid uuid:=(select id from content_fixture where k='v2'); begin
 perform review_content_version(gen_random_uuid(),vid,'INTERNAL','CHANGES_REQUESTED','Revise caption');
 denied:=false; begin perform review_content_version(gen_random_uuid(),vid,'INTERNAL','APPROVED','Overwrite decision'); exception when unique_violation then denied:=true; end;
 if not denied then raise exception 'Decision overwritten'; end if;
 perform save_content_plan((select id from content_fixture where k='task'),1,jsonb_set((select plan from content_payload),'{brief}','"Changed brief"'));
 denied:=false; begin perform review_content_version(gen_random_uuid(),vid,'CLIENT','APPROVED','Stale plan','Client'); exception when serialization_failure then denied:=true; end;
 if not denied then raise exception 'Stale plan reviewed'; end if;
 perform add_content_version((select id from content_fixture where k='v3'),(select id from content_fixture where k='task'),2,2,'PM authored caption');
 denied:=false; begin perform review_content_version(gen_random_uuid(),(select id from content_fixture where k='v3'),'INTERNAL','APPROVED','PM self approval'); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Manager self-approved'; end if;
end $$;
reset role;
-- A member cannot write unassigned work; NULL assignment must fail closed.
update project_task set "assignedUserId"=null where id=(select id from content_fixture where k='task');
select set_config('request.jwt.claim.sub',(select id::text from content_fixture where k='contributor'),true);
set local role authenticated;
do $$ declare denied boolean:=false; begin
 begin perform add_content_version(gen_random_uuid(),(select id from content_fixture where k='task'),3,2,'Unassigned write'); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Unassigned member authored'; end if;
end $$;
reset role;
update project_member set active=false where "projectId"=(select id from content_fixture where k='project');
set local role authenticated;
do $$ begin
 if exists(select 1 from content_version where "taskId"=(select id from content_fixture where k='task')) then raise exception 'Revoked member sees versions'; end if;
 if exists(select 1 from content_review where "versionId"=(select id from content_fixture where k='v1')) then raise exception 'Revoked member sees reviews'; end if;
 if exists(select 1 from content_publication where "versionId"=(select id from content_fixture where k='v1')) then raise exception 'Revoked member sees publications'; end if;
end $$;
reset role;
select 'Version immutability, approval gates, reapproval, retry and access checks passed' as result;
